### ISSUE TITLE
Gerenciar Tarefas

### ISSUE THREAD

**Issue by wendelbartz** [Thaylles/Projeto_Corretor#1]
Todas as tarefas serão postadas aqui.

**Comment by wendelbartz** [comment]
Criar um programa que iguale palavras com a do dicionario
Criar um método que ache palavras parecidas com as palavras erradas
Criar o programa dos sinônimos
Criar a página principal do site(home)
Criar a página de correção(corrigindo)
Criar a página de finalização(corrigido)
Criar a página de sugerir sinônimos
Criar Spark

**Comment by Thaylles** [comment]
https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Java

http://rosettacode.org/wiki/Levenshtein_distance

Algoritmos para ver o quanto a palavra é proxima a outra.

**Comment by RodrigoGandra** [comment]
Metas para 23/9
Criar um  método para persistência
Criar um método para listar os arquivos persistidos
Criar uma outra interação(excluir,editar..)
Responsáveis a decidir.
