### ISSUE TITLE
Home implementada, necessito de um tester

### ISSUE THREAD

**Issue by RodrigoGandra** [Thaylles/Projeto_Corretor#10]
A home foi implementada, por enquanto ela redireciona para ela mesmo quando o texto é enviado, necessito que um contribuidor teste ela para ver se os arquivos .txt estão sendo salvos.

**Comment by Thaylles** [comment]
/home testado. Funcionando até o momento.
*OBS : Deveria ter um limite de caracteres para a frase/texto.

**Comment by RodrigoGandra** [comment]
o limite foi implementado, irei dar o push, em caso de erros a issue será re-aberta.
