### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by Thaylles** [Thaylles/Projeto_Corretor#12]
Galera, fiz um pouco do distance. Amanhã vou continua-lo. E também, centralizei o home. Mas acho que ainda não é assim que idealizamos. 
Distance está colocando palavras na matriz, mas por hora, ainda está pegando as primeiras palavras e ainda não as menores, Pretendo corri-lo amanhã.

**Comment by RodrigoGandra** [comment]
Distance  continua em andamento,  faltam  poucos reajustes mas está em sua etapa final.
