### ISSUE TITLE
Criando um html com design para teste

### ISSUE THREAD

**Issue by wendelbartz** [Thaylles/Projeto_Corretor#13]
Estou criando alguns html para a fim de testes por algum usuario.

**Comment by wendelbartz** [comment]
Enviado. Aguardando testes...

**Comment by wendelbartz** [comment]
Foi descoberto a necessidade trocar o radio para checkbox no html e também é necessessario que contenha mais informações sobre o que fazer no site

**Comment by RodrigoGandra** [comment]
Não pode ser checkbox devido ao fato de que só uma alternativa deve ser selecionada, a princípio vamos manter radio com uma acesskey definida em cada opção para que o usuário navegue entre elas e realize o submit através do enter. As acesskeys de cada opção deverão ser especificadas em texto plano (uma espécie de legenda), no html para que leitores de tela possam lê-las. Acabei de upar o html com as acesskeys já setadas,  só faltam as instruções, irei fechar a Issue e implementar a legenda, em caso de problemas a Issue poderá vir a ser re-aberta.
