### ISSUE TITLE
Levinsthein pronto

### ISSUE THREAD

**Issue by Thaylles** [Thaylles/Projeto_Corretor#16]
Mas como eu fiz uma exceção para palavras com o til, acredito que terei que fazer para o "ç". Testem algumas palavras e vejam se acham necessário. O til é indica a nasalização da vogal e o ç sibilante alveolar surda. São duas exceções no português muito importantes além do z, ss, sc, que não teríamos como botar todas regras. Mas testem e julguem se necessário.
obs : palavras como 'coracao' sem til e sem cedilha, não aparece, mas caso tenha til, aparece. E palavras grandes como 'excecoes' aparece as duas coisas.

**Comment by RodrigoGandra** [comment]
Levenshtein funcional. Issue fechada.
