### ISSUE TITLE
Testar método de adição de textos

### ISSUE THREAD

**Issue by wendelbartz** [Thaylles/Projeto_Corretor#3]
Deve ser testado por qualquer pessoa

**Comment by RodrigoGandra** [comment]
Método testado , quase funcional , apenas falta a adição de um método GET para ter uma rota funcional.

**Comment by wendelbartz** [comment]
Corrigido e esperando o teste novamente.

**Comment by RodrigoGandra** [comment]
Testado e está funcional, Issue fechada.
