### ISSUE TITLE
Testar método da listagem dos textos

### ISSUE THREAD

**Issue by RodrigoGandra** [Thaylles/Projeto_Corretor#5]
Necessito que algum colaborador teste o novo método de listagem implementado recentemente.

**Comment by RodrigoGandra** [comment]
O método não poderá ser testado por hora em ventura de modificações, a issue será reaberta posteriormente para teste do mesmo.

**Comment by RodrigoGandra** [comment]
O método foi atualizado e algumas outras funções implementadas e estão no aguardo de algum tester.

**Comment by Thaylles** [comment]
Testado e aprovado.
